import {
    LayoutGrid,
    Folder,
    FileText,
    Settings,
    Users,
    Home,
    Bell,
    Calendar,
    Mail,
    Search,
    Star,
    Heart,
    Bookmark,
    Tag,
    Clock,
    CheckCircle,
    AlertCircle,
    Info,
    HelpCircle,
    ExternalLink,
    Link,
    Image,
    Video,
    Music,
    Download,
    Upload,
    Share,
    Edit,
    Trash,
    Plus,
    Minus,
    X,
    Check,
    ChevronRight,
    ChevronLeft,
    ChevronDown,
    ChevronUp,
    ArrowRight,
    ArrowLeft,
    ArrowUp,
    ArrowDown,
    Menu,
    MoreHorizontal,
    MoreVertical,
    Grid,
    List,
    Eye,
    EyeOff,
    Lock,
    Unlock,
    Key,
    Shield,
    User,
    UserPlus,
    UserMinus,
    UserCheck,
    Briefcase,
    Building,
    MapPin,
    Phone,
    Smartphone,
    Laptop,
    Monitor,
    Printer,
    Camera,
    Mic,
    Headphones,
    Speaker,
    Wifi,
    Bluetooth,
    Battery,
    Power,
    Zap,
    Sun,
    Moon,
    Cloud,
    CloudRain,
    Umbrella,
    Thermometer,
    Wind,
    Droplet,
    Flame,
    Snowflake,
    Globe,
    Map,
    Compass,
    Flag,
    Target,
    Award,
    Trophy,
    Gift,
    ShoppingCart,
    ShoppingBag,
    CreditCard,
    DollarSign,
    Percent,
    TrendingUp,
    TrendingDown,
    BarChart,
    PieChart,
    Activity,
    Layers,
    Box,
    Package,
    Archive,
    Database,
    Server,
    HardDrive,
    Cpu,
    Terminal,
    Code,
    CodepenIcon,
    GitBranch,
    GitCommit,
    GitMerge,
    GitPullRequest,
    type LucideIcon,
} from 'lucide-react';

export const iconOptions: { name: string; icon: LucideIcon }[] = [
    { name: 'LayoutGrid', icon: LayoutGrid },
    { name: 'Folder', icon: Folder },
    { name: 'FileText', icon: FileText },
    { name: 'Settings', icon: Settings },
    { name: 'Users', icon: Users },
    { name: 'Home', icon: Home },
    { name: 'Bell', icon: Bell },
    { name: 'Calendar', icon: Calendar },
    { name: 'Mail', icon: Mail },
    { name: 'Search', icon: Search },
    { name: 'Star', icon: Star },
    { name: 'Heart', icon: Heart },
    { name: 'Bookmark', icon: Bookmark },
    { name: 'Tag', icon: Tag },
    { name: 'Clock', icon: Clock },
    { name: 'CheckCircle', icon: CheckCircle },
    { name: 'AlertCircle', icon: AlertCircle },
    { name: 'Info', icon: Info },
    { name: 'HelpCircle', icon: HelpCircle },
    { name: 'ExternalLink', icon: ExternalLink },
    { name: 'Link', icon: Link },
    { name: 'Image', icon: Image },
    { name: 'Video', icon: Video },
    { name: 'Music', icon: Music },
    { name: 'Download', icon: Download },
    { name: 'Upload', icon: Upload },
    { name: 'Share', icon: Share },
    { name: 'Edit', icon: Edit },
    { name: 'Trash', icon: Trash },
    { name: 'Plus', icon: Plus },
    { name: 'Minus', icon: Minus },
    { name: 'X', icon: X },
    { name: 'Check', icon: Check },
    { name: 'ChevronRight', icon: ChevronRight },
    { name: 'ChevronLeft', icon: ChevronLeft },
    { name: 'ChevronDown', icon: ChevronDown },
    { name: 'ChevronUp', icon: ChevronUp },
    { name: 'ArrowRight', icon: ArrowRight },
    { name: 'ArrowLeft', icon: ArrowLeft },
    { name: 'ArrowUp', icon: ArrowUp },
    { name: 'ArrowDown', icon: ArrowDown },
    { name: 'Menu', icon: Menu },
    { name: 'MoreHorizontal', icon: MoreHorizontal },
    { name: 'MoreVertical', icon: MoreVertical },
    { name: 'Grid', icon: Grid },
    { name: 'List', icon: List },
    { name: 'Eye', icon: Eye },
    { name: 'EyeOff', icon: EyeOff },
    { name: 'Lock', icon: Lock },
    { name: 'Unlock', icon: Unlock },
    { name: 'Key', icon: Key },
    { name: 'Shield', icon: Shield },
    { name: 'User', icon: User },
    { name: 'UserPlus', icon: UserPlus },
    { name: 'UserMinus', icon: UserMinus },
    { name: 'UserCheck', icon: UserCheck },
    { name: 'Briefcase', icon: Briefcase },
    { name: 'Building', icon: Building },
    { name: 'MapPin', icon: MapPin },
    { name: 'Phone', icon: Phone },
    { name: 'Smartphone', icon: Smartphone },
    { name: 'Laptop', icon: Laptop },
    { name: 'Monitor', icon: Monitor },
    { name: 'Printer', icon: Printer },
    { name: 'Camera', icon: Camera },
    { name: 'Mic', icon: Mic },
    { name: 'Headphones', icon: Headphones },
    { name: 'Speaker', icon: Speaker },
    { name: 'Wifi', icon: Wifi },
    { name: 'Bluetooth', icon: Bluetooth },
    { name: 'Battery', icon: Battery },
    { name: 'Power', icon: Power },
    { name: 'Zap', icon: Zap },
    { name: 'Sun', icon: Sun },
    { name: 'Moon', icon: Moon },
    { name: 'Cloud', icon: Cloud },
    { name: 'CloudRain', icon: CloudRain },
    { name: 'Umbrella', icon: Umbrella },
    { name: 'Thermometer', icon: Thermometer },
    { name: 'Wind', icon: Wind },
    { name: 'Droplet', icon: Droplet },
    { name: 'Flame', icon: Flame },
    { name: 'Snowflake', icon: Snowflake },
    { name: 'Globe', icon: Globe },
    { name: 'Map', icon: Map },
    { name: 'Compass', icon: Compass },
    { name: 'Flag', icon: Flag },
    { name: 'Target', icon: Target },
    { name: 'Award', icon: Award },
    { name: 'Trophy', icon: Trophy },
    { name: 'Gift', icon: Gift },
    { name: 'ShoppingCart', icon: ShoppingCart },
    { name: 'ShoppingBag', icon: ShoppingBag },
    { name: 'CreditCard', icon: CreditCard },
    { name: 'DollarSign', icon: DollarSign },
    { name: 'Percent', icon: Percent },
    { name: 'TrendingUp', icon: TrendingUp },
    { name: 'TrendingDown', icon: TrendingDown },
    { name: 'BarChart', icon: BarChart },
    { name: 'PieChart', icon: PieChart },
    { name: 'Activity', icon: Activity },
    { name: 'Layers', icon: Layers },
    { name: 'Box', icon: Box },
    { name: 'Package', icon: Package },
    { name: 'Archive', icon: Archive },
    { name: 'Database', icon: Database },
    { name: 'Server', icon: Server },
    { name: 'HardDrive', icon: HardDrive },
    { name: 'Cpu', icon: Cpu },
    { name: 'Terminal', icon: Terminal },
    { name: 'Code', icon: Code },
    { name: 'CodepenIcon', icon: CodepenIcon },
    { name: 'GitBranch', icon: GitBranch },
    { name: 'GitCommit', icon: GitCommit },
    { name: 'GitMerge', icon: GitMerge },
    { name: 'GitPullRequest', icon: GitPullRequest },
];

export const getIconComponent = (iconName: string): LucideIcon | null => {
    const found = iconOptions.find((opt) => opt.name === iconName);
    return found ? found.icon : null;
};
